server:
  port: 8012

spring:
  profiles:
    active: local
  application:
    name: crypto-payments
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://127.0.0.1:3306/rate-limiter?useUnicode=true&characterEncoding=utf8&useSSL=false
    databaseName:
    serverName:
    username: root
    password:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      generate_statistics: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.time_zone: Asia/Kolkata

redis:
  redissonConfigPath: classpath:redisson/redissonconfig-local.yml
  hostName: localhost
  pass:
  port: 6379
  pool:
    maxTotal: 10
    minIdle: 10
    maxIdle: 10


